# config/routes.yaml

# the "app_lucky_number" route name is not important yet
#app_lucky_number:
#  #host:       "{subdomain}.example.com"
#  path: /lucky/number/{repeater}
#  controller: App\Controller\LuckyController::number
#  methods: GET
#  defaults:
#    repeater: 1
#  requirements:
#    repeater: '\d+'
#    extraParameterSample: "Hello world!"
#    #locale: 'en|tr'
#    #subdomain: m|mobile
#  #locale:      en
#  #format: html
#  #schemes:    [https]
#
#site_content_show:
#  host: "{subdomain}.%domain%"
#  path: "/{slug}.htm"
#  controller: App\Controller\Site\ContentController::show
#  requirements:
#    slug: .*
#    subdomain: ^(?!www).+

main:
  path: /
  controller: App\Controller\MainController::index

# BLOG

blog_index:
  path: /blog
  controller: App\Controller\BlogController::index
  methods: GET

blog_edit:
  path: /blog/{id}/edit
  controller: App\Controller\BlogController::edit
  methods: [GET, POST, PATCH]

blog_delete:
  path: /blog/{id}
  controller: App\Controller\BlogController::delete
  methods: DELETE

blog_new:
  path: /blog/new
  controller: App\Controller\BlogController::new
  methods: [GET, POST]

blog_show:
  path: /blog/{id}
  controller: App\Controller\BlogController::show

# NEWS

news_index:
  path: /news
  controller: App\Controller\NewsController::index
  methods: GET

news_edit:
  path: /news/{id}/edit
  controller: App\Controller\NewsController::edit
  methods: [GET, POST]

news_delete:
  path: /news/{id}
  controller: App\Controller\NewsController::delete
  methods: DELETE

news_new:
  path: /news/new
  controller: App\Controller\NewsController::new
  methods: [GET, POST]

news_show:
  path: /news/{id}
  controller: App\Controller\NewsController::show
  methods: GET

# SLUG

slug_index:
  path: /slug
  controller: App\Controller\SlugController::index
  methods: GET

slug_new:
  path: /slug/new
  controller: App\Controller\SlugController::new
  methods: [GET, POST]

slug_edit:
  path: /slug/{id}/edit
  controller: App\Controller\SlugController::edit
  methods: [GET, POST, PATCH]

slug_delete:
  path: /slug/{id}
  controller: App\Controller\SlugController::delete
  methods: DELETE

slug_show:
  path: /slug/{id}
  controller: App\Controller\SlugController::show

# SLUG SITE

site_show:
  path: /{slug}/{page}
  controller: App\Controller\MainController::show
  defaults:
    page: 1